name: Monitor Checks for Snippets Repo

on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 15 minutes
  workflow_dispatch:        # Allows manual trigger

jobs:
  monitor-checks:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Test Repo
        uses: actions/checkout@v3

      # Step 2: Fetch the latest commit SHA from the snippets repo
      - name: Fetch Latest Commit SHA
        run: |
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/tscircuit/snippets/commits/main \
            | jq -r '.sha' > latest_commit_sha.txt
          echo "Latest Commit SHA fetched: $(cat latest_commit_sha.txt)"

      # Step 3: Fetch check runs for the latest commit
      - name: Fetch Check Runs
        run: |
          LATEST_COMMIT_SHA=$(cat latest_commit_sha.txt)
          curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/tscircuit/snippets/commits/${LATEST_COMMIT_SHA}/check-runs \
            > check_runs.json
          echo "Check Runs Fetched for Commit: ${LATEST_COMMIT_SHA}"

      # Step 4: Parse and Notify about Check Runs
      - name: Analyze and Notify
        run: |
          STATUS=$(jq -r '.check_runs[] | .status' check_runs.json)
          CONCLUSION=$(jq -r '.check_runs[] | .conclusion' check_runs.json)
          OUTPUT="Check Runs Status:\n"
          for i in $(seq 0 $(jq '.check_runs | length - 1' check_runs.json)); do
            NAME=$(jq -r ".check_runs[$i].name" check_runs.json)
            STATUS=$(jq -r ".check_runs[$i].status" check_runs.json)
            CONCLUSION=$(jq -r ".check_runs[$i].conclusion" check_runs.json)
            OUTPUT="${OUTPUT}\n${NAME}: ${STATUS} (${CONCLUSION})"
          done
          echo -e "${OUTPUT}"

          # Send Notification to Discord
          curl -H "Content-Type: application/json" \
               -X POST -d "{\"content\": \"GitHub Checks for Commit ${LATEST_COMMIT_SHA}:\n${OUTPUT}\"}" \
               ${{ secrets.DISCORD_WEBHOOK_URL }}
